version: '2'
services:
    sioe-app:
        image: sioe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://sioe-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=SIOE
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sioe-mongodb:
        extends:
            file: mongodb.yml
            service: sioe-mongodb
